version: '2'
services:
  database_6:
    image: postgres:9.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=amorphic
      - POSTGRES_PASSWORD=amorphic
      - POSTGRES_DB=persistor_banking_6
# uncomment to save data between tests
#    volumes:
#      - ./.postgres_6:/var/lib/postgresql/data
  mongo:
    image: mongo:3.4
    ports:
      - '27017:27017'
# uncomment to save data between tests
#    volumes:
#      - ./.mongo:/data/db
  amorphic-test-node-6:
    build:
      context: .
      dockerfile: Dockerfile-node-6
    image: amorphic-test-node-6:latest
    depends_on:
      - mongo
      - database_6
    env_file:
      - ./test-node-6.env
    command: ./wait-for-it.sh database_6:5432 -- ./wait-for-it.sh mongo:27017 -- npm run test    
 